# Generated by Django 3.2.9 on 2021-11-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=2)),
                ('track', models.CharField(max_length=50)),
            ],
        ),
    ]
