# Generated by Django 3.2.9 on 2021-11-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_students_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('passw', models.IntegerField(max_length=20)),
            ],
        ),
    ]
